import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../core/theme.dart';
import '../core/widgets/glass_container.dart';
import '../providers/user_provider.dart';
import '../services/haptic_service.dart';
import '../services/supabase_service.dart';
import 'nfc_payment_screen.dart';
import 'bluetooth_payment_screen.dart';

class ReceivePaymentScreen extends ConsumerStatefulWidget {
  const ReceivePaymentScreen({super.key});

  @override
  ConsumerState<ReceivePaymentScreen> createState() => _ReceivePaymentScreenState();
}

class _ReceivePaymentScreenState extends ConsumerState<ReceivePaymentScreen> {
  final _amountController = TextEditingController();
  String? _bolt11;
  bool _isLoading = false;

  Future<void> _generateInvoice() async {
    final amount = double.tryParse(_amountController.text) ?? 0;
    if (amount <= 0) return;

    setState(() => _isLoading = true);
    HapticService.selection();

    try {
      final amountSats = ((amount / 70000.0) * 100000000).round();
      if (amountSats <= 0) throw Exception('Montant invalide');

      final breez = ref.read(breezServiceProvider);
      final response = await breez.createInvoice(
        amountSats: amountSats,
        description: 'Facture Crypto-Pay',
      );

      final bolt11 = response.lnInvoice.bolt11;
      final paymentHash = response.lnInvoice.paymentHash ?? null;

      // Record pending invoice in Supabase so webhook can match it later
      final authState = ref.read(authProvider);
      final userId = authState.user?['user_id'] as String?;
      if (userId != null) {
        final supabase = ref.read(supabaseServiceProvider);
        final amountUsd = double.tryParse(_amountController.text.replaceAll(',', '.')) ?? 0.0;
        await supabase.recordPendingInvoice(
          userId: userId,
          amountUsd: amountUsd,
          amountSats: amountSats,
          bolt11: bolt11,
          paymentHash: paymentHash,
          note: 'Invoice generated by app',
        );
      }

      setState(() => _bolt11 = bolt11);
      HapticService.success();
    } catch (e) {
      debugPrint('Invoice error: $e');
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Erreur de génération de facture : $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final authState = ref.watch(authProvider);
    final userAddress = "CP-${authState.user?['referral_code'] ?? '123456'}";

    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        title: const Text('Recevoir'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(LiquidGlassTheme.marginPage),
        child: Column(
          children: [
            _buildQRCodeSection(userAddress),
            const SizedBox(height: 32),
            _buildRequestSection(),
            const SizedBox(height: 32),
            _buildNfcBluetoothReceiveSection(),
            const SizedBox(height: 32),
            _buildExternalLinksSection(),
          ],
        ),
      ),
    );
  }

  Widget _buildNfcBluetoothReceiveSection() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          'Recevoir sans contact',
          style: TextStyle(color: Colors.white60, fontWeight: FontWeight.bold, fontSize: 14),
        ),
        const SizedBox(height: 12),
        Row(
          children: [
            Expanded(
              child: GestureDetector(
                onTap: () {
                  HapticService.selection();
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (_) => const NfcPaymentScreen(initialReceiving: true),
                    ),
                  );
                },
                child: GlassContainer(
                  padding: const EdgeInsets.all(16),
                  borderRadius: 20,
                  opacity: 0.08,
                  child: Column(
                    children: const [
                      Icon(Icons.nfc, color: LiquidGlassTheme.accent, size: 32),
                      SizedBox(height: 8),
                      Text('Via NFC', style: TextStyle(fontWeight: FontWeight.bold, color: Colors.white)),
                      SizedBox(height: 4),
                      Text('Approcher tag', style: TextStyle(color: Colors.white38, fontSize: 11)),
                    ],
                  ),
                ),
              ),
            ),
            const SizedBox(width: 16),
            Expanded(
              child: GestureDetector(
                onTap: () {
                  HapticService.selection();
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (_) => const BluetoothPaymentScreen(initialReceiving: true),
                    ),
                  );
                },
                child: GlassContainer(
                  padding: const EdgeInsets.all(16),
                  borderRadius: 20,
                  opacity: 0.08,
                  child: Column(
                    children: const [
                      Icon(Icons.bluetooth, color: Colors.blue, size: 32),
                      SizedBox(height: 8),
                      Text('Via Bluetooth', style: TextStyle(fontWeight: FontWeight.bold, color: Colors.white)),
                      SizedBox(height: 4),
                      Text('BLE sans fil', style: TextStyle(color: Colors.white38, fontSize: 11)),
                    ],
                  ),
                ),
              ),
            ),
          ],
        ),
      ],
    );
  }

  Widget _buildQRCodeSection(String address) {
    return Column(
      children: [
        GlassContainer(
          padding: const EdgeInsets.all(24),
          borderRadius: 32,
          child: Column(
            children: [
              Container(
                width: 200,
                height: 200,
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(20),
                ),
                child: const Icon(Icons.qr_code_2, size: 180, color: Colors.black),
              ),
              const SizedBox(height: 24),
              Text(address, style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold, letterSpacing: 1)),
              const SizedBox(height: 8),
              const Text('Votre ID Crypto-Pay unique', style: TextStyle(color: Colors.white38, fontSize: 12)),
            ],
          ),
        ),
        const SizedBox(height: 16),
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            _actionIconButton(Icons.copy, 'Copier'),
            const SizedBox(width: 24),
            _actionIconButton(Icons.share, 'Partager'),
          ],
        ),
      ],
    );
  }

  Widget _actionIconButton(IconData icon, String label) {
    return Column(
      children: [
        GlassContainer(
          padding: const EdgeInsets.all(12),
          borderRadius: 16,
          opacity: 0.1,
          child: Icon(icon, color: Colors.white70),
        ),
        const SizedBox(height: 8),
        Text(label, style: const TextStyle(color: Colors.white38, fontSize: 12)),
      ],
    );
  }

  Widget _buildRequestSection() {
    return GlassContainer(
      padding: const EdgeInsets.all(20),
      borderRadius: 24,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text('Demander un montant', style: TextStyle(fontWeight: FontWeight.bold)),
          const SizedBox(height: 16),
          Row(
            children: [
              Expanded(
                child: TextField(
                  controller: _amountController,
                  keyboardType: TextInputType.number,
                  style: const TextStyle(color: Colors.white),
                  decoration: const InputDecoration(
                    hintText: '0.00',
                    prefixText: '\$ ',
                    border: InputBorder.none,
                  ),
                ),
              ),
              if (_isLoading)
                const CircularProgressIndicator(color: LiquidGlassTheme.accent)
              else
                IconButton(
                  onPressed: _generateInvoice,
                  icon: const Icon(Icons.arrow_forward, color: LiquidGlassTheme.accent),
                ),
            ],
          ),
          if (_bolt11 != null) ...[
            const Divider(color: Colors.white10),
            const SizedBox(height: 8),
            SelectableText(
              _bolt11!,
              style: const TextStyle(color: Colors.white70, fontSize: 12),
            ),
            const SizedBox(height: 12),
            Row(
              mainAxisAlignment: MainAxisAlignment.end,
              children: [
                TextButton.icon(
                  onPressed: () {
                    HapticService.selection();
                    Clipboard.setData(ClipboardData(text: _bolt11!));
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(content: Text('Facture copiée')),
                    );
                  },
                  icon: const Icon(Icons.copy, size: 18, color: Colors.white70),
                  label: const Text('Copier', style: TextStyle(color: Colors.white70)),
                ),
              ],
            ),
          ],
        ],
      ),
    );
  }

  Widget _buildExternalLinksSection() {
    final authState = ref.watch(authProvider);
    return Column(
      children: [
        Material(
          color: Colors.transparent,
          child: ListTile(
            leading: const Icon(Icons.bolt, color: Colors.orange),
            title: const Text('Adresse Lightning'),
            subtitle: Text(authState.user?['email'] ?? '—'),
            trailing: const Icon(Icons.chevron_right, color: Colors.white24),
            onTap: () {
              HapticService.selection();
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(content: Text('Adresse Lightning non disponible pour le moment')),
              );
            },
          ),
        ),
      ],
    );
  }
}
